spring:
  datasource:
    url: jdbc:postgresql://db.xoxrtruyomxhaurbtrvy.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: 2nHUfX1O8Wo3DM4X
    hikari:
      maximum-pool-size: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
